import { diamond, plus, rect, uniqueCells } from './geometry';
import type { BeaconType, Cell, Placement, PuzzleDefinition } from './types';

const p = (x: number, y: number, type: BeaconType, locked = false): Placement =>
  locked ? { x, y, type, locked: true } : { x, y, type };

function define(
  puzzle: Omit<PuzzleDefinition, 'locked' | 'blocked'> & {
    locked?: Placement[];
    blocked?: Cell[];
  },
): PuzzleDefinition {
  const locked = (puzzle.locked ?? []).map((item) => ({ ...item, locked: true as const }));
  return {
    ...puzzle,
    blocked: puzzle.blocked ?? [],
    locked,
    solution: puzzle.solution.map((item) =>
      locked.some((lock) => lock.x === item.x && lock.y === item.y) ? { ...item, locked: true } : item,
    ),
  };
}

export const PUZZLES: PuzzleDefinition[] = [
  define({
    id: 'bl-01-first-plus',
    title: 'First plus',
    width: 5,
    height: 5,
    difficulty: 'intro',
    required: plus(2, 2, 1),
    available: ['cross'],
    inventory: { cross: 1 },
    solution: [p(2, 2, 'cross')],
    par: 1,
    unique: true,
    lesson: 'A Cross covers its cell and the four orthogonal neighbors.',
    note: 'Place one Cross so the plus-shaped lattice is covered exactly once.',
  }),
  define({
    id: 'bl-02-long-plus',
    title: 'Long plus',
    width: 5,
    height: 5,
    difficulty: 'intro',
    required: plus(2, 2, 2),
    available: ['cross'],
    inventory: { cross: 4 },
    solution: [p(2, 0, 'cross'), p(0, 2, 'cross'), p(3, 2, 'cross'), p(2, 4, 'cross')],
    par: 4,
    lesson: 'A full-width plus cannot be covered by a single center Cross.',
    note: 'The arms reach the board edge. One Cross cannot finish every tip.',
  }),
  define({
    id: 'bl-03-tee',
    title: 'The tee',
    width: 5,
    height: 5,
    difficulty: 'intro',
    required: uniqueCells(rect(0, 0, 4, 0), rect(2, 1, 2, 4)),
    available: ['cross'],
    inventory: { cross: 4 },
    solution: [p(0, 0, 'cross'), p(2, 1, 'cross'), p(4, 0, 'cross'), p(2, 4, 'cross')],
    par: 4,
    lesson: 'A T-shaped lattice forces Cross placements at the bar ends and stem.',
    note: 'Read the three-way junction before spending the last Cross.',
  }),
  define({
    id: 'bl-04-ell',
    title: 'The ell',
    width: 5,
    height: 5,
    difficulty: 'intro',
    required: uniqueCells(rect(0, 0, 0, 4), rect(1, 4, 4, 4)),
    available: ['cross'],
    inventory: { cross: 3 },
    solution: [p(0, 1, 'cross'), p(0, 4, 'cross'), p(3, 4, 'cross')],
    par: 3,
    lesson: 'An L-shaped lattice is covered with fewer Cross beacons than a tee.',
    note: 'The corner cell can belong to either arm. Cover it once.',
  }),
  define({
    id: 'bl-05-first-diamond',
    title: 'First diamond',
    width: 5,
    height: 5,
    difficulty: 'developing',
    required: diamond(2, 2),
    available: ['diagonal'],
    inventory: { diagonal: 1 },
    solution: [p(2, 2, 'diagonal')],
    par: 1,
    unique: true,
    lesson: 'A Diagonal covers its cell and the four diagonal neighbors.',
    note: 'This lattice matches one Diagonal. Other origins leave a gap.',
  }),
  define({
    id: 'bl-06-plus-or-diamond',
    title: 'Plus or diamond',
    width: 5,
    height: 5,
    difficulty: 'developing',
    required: plus(2, 2, 2),
    available: ['cross', 'diagonal'],
    inventory: { cross: 4, diagonal: 2 },
    solution: [p(2, 0, 'cross'), p(0, 2, 'cross'), p(3, 2, 'cross'), p(2, 4, 'cross')],
    par: 4,
    lesson: 'A Diagonal is available, but the long plus still closes with four Cross beacons.',
    note: 'Both types are legal on most cells. Inventory still limits the mix.',
  }),
  define({
    id: 'bl-07-mixed-tee',
    title: 'Mixed tee',
    width: 5,
    height: 5,
    difficulty: 'developing',
    required: uniqueCells(rect(0, 0, 4, 0), rect(2, 1, 2, 4)),
    available: ['cross', 'diagonal'],
    inventory: { cross: 3, diagonal: 2 },
    solution: [p(0, 0, 'cross'), p(3, 0, 'cross'), p(2, 2, 'cross'), p(2, 4, 'diagonal')],
    par: 4,
    lesson: 'On a tee, mixing one Diagonal with Cross beacons can shorten the cover.',
    note: 'Compare a Cross and a Diagonal on the junction before placing.',
  }),
  define({
    id: 'bl-08-mixed-ell',
    title: 'Mixed ell',
    width: 5,
    height: 5,
    difficulty: 'developing',
    required: uniqueCells(rect(0, 0, 0, 4), rect(1, 4, 4, 4)),
    available: ['cross', 'diagonal'],
    inventory: { cross: 3, diagonal: 2 },
    solution: [p(0, 1, 'cross'), p(0, 4, 'cross'), p(3, 4, 'cross')],
    par: 3,
    lesson: 'Mixing types on an L changes which leftover gaps remain.',
    note: 'A Diagonal never covers an orthogonal neighbor.',
  }),
  define({
    id: 'bl-09-across-the-row',
    title: 'Across the row',
    width: 5,
    height: 5,
    difficulty: 'mixed',
    required: rect(0, 2, 4, 2),
    available: ['horizontal'],
    inventory: { horizontal: 2 },
    solution: [p(0, 2, 'horizontal'), p(3, 2, 'horizontal')],
    par: 2,
    lesson: 'A Horizontal covers only three cells in its row.',
    note: 'Five required cells in one row need more than one bar.',
  }),
  define({
    id: 'bl-10-down-the-column',
    title: 'Down the column',
    width: 5,
    height: 5,
    difficulty: 'mixed',
    required: rect(2, 0, 2, 4),
    available: ['vertical'],
    inventory: { vertical: 2 },
    solution: [p(2, 0, 'vertical'), p(2, 3, 'vertical')],
    par: 2,
    lesson: 'A Vertical covers only three cells in its column.',
    note: 'The same counting problem, now upright.',
  }),
  define({
    id: 'bl-11-three-rows',
    title: 'Three rows',
    width: 5,
    height: 5,
    difficulty: 'mixed',
    required: rect(0, 1, 4, 3),
    available: ['horizontal', 'vertical'],
    inventory: { horizontal: 8, vertical: 8 },
    solution: [
      p(0, 1, 'horizontal'),
      p(2, 1, 'vertical'),
      p(3, 1, 'vertical'),
      p(4, 1, 'vertical'),
      p(0, 2, 'horizontal'),
      p(0, 3, 'horizontal'),
      p(3, 3, 'horizontal'),
    ],
    par: 7,
    lesson: 'Horizontal and Vertical bars can share a band without a Cross.',
    note: 'A Vertical started on the top row also covers the rows below.',
  }),
  define({
    id: 'bl-12-open-field',
    title: 'Open field',
    width: 5,
    height: 5,
    difficulty: 'mixed',
    available: ['horizontal', 'vertical'],
    inventory: { horizontal: 8, vertical: 8 },
    solution: [
      p(0, 0, 'horizontal'),
      p(2, 0, 'vertical'),
      p(3, 0, 'vertical'),
      p(4, 0, 'vertical'),
      p(0, 1, 'horizontal'),
      p(0, 2, 'horizontal'),
      p(3, 2, 'horizontal'),
      p(0, 3, 'horizontal'),
      p(3, 3, 'horizontal'),
      p(0, 4, 'horizontal'),
      p(3, 4, 'horizontal'),
    ],
    par: 11,
    lesson: 'A full 5×5 can be tiled with bars alone.',
    note: 'Every cell of this board is required. There is no void frame.',
  }),
  define({
    id: 'bl-13-hub-rule',
    title: 'Hub rule',
    width: 5,
    height: 5,
    difficulty: 'constrained',
    required: plus(2, 2, 2),
    available: ['cross', 'diagonal'],
    inventory: { cross: 4, diagonal: 1 },
    allowedTypesByCell: { '2,2': ['diagonal'] },
    solution: [p(2, 0, 'cross'), p(0, 2, 'cross'), p(3, 2, 'cross'), p(2, 4, 'cross')],
    par: 4,
    lesson: 'If you occupy the hub it must be a Diagonal, but a neighbor Cross can cover it instead.',
    note: 'The center cell accepts only a Diagonal if you place there.',
  }),
  define({
    id: 'bl-14-plus-and-base',
    title: 'Plus and base',
    width: 5,
    height: 5,
    difficulty: 'constrained',
    required: uniqueCells(plus(2, 2, 1), rect(0, 4, 4, 4)),
    available: ['cross', 'horizontal'],
    inventory: { cross: 2, horizontal: 3 },
    solution: [p(2, 2, 'cross'), p(0, 4, 'cross'), p(3, 4, 'horizontal')],
    par: 3,
    lesson: 'A connected plus-and-base can be finished with bars plus two Cross beacons.',
    note: 'The bottom row is part of the same lattice, not a separate puzzle.',
  }),
  define({
    id: 'bl-15-three-tools',
    title: 'Three tools',
    width: 5,
    height: 5,
    difficulty: 'constrained',
    required: uniqueCells(rect(0, 0, 4, 0), rect(2, 1, 2, 4)),
    available: ['cross', 'horizontal', 'vertical'],
    inventory: { cross: 1, horizontal: 2, vertical: 2 },
    solution: [p(0, 0, 'cross'), p(2, 0, 'vertical'), p(4, 0, 'horizontal'), p(2, 3, 'vertical')],
    par: 4,
    lesson: 'One Cross, two bars of each kind. Waste the Cross and the tee will not close.',
    note: 'Spend the single Cross where a bar cannot finish a corner.',
  }),
  define({
    id: 'bl-16-named-origins',
    title: 'Named origins',
    width: 5,
    height: 5,
    difficulty: 'constrained',
    required: rect(0, 1, 4, 3),
    available: ['horizontal', 'vertical'],
    inventory: { horizontal: 8, vertical: 8 },
    allowedCells: [
      { x: 0, y: 1 },
      { x: 2, y: 1 },
      { x: 3, y: 1 },
      { x: 4, y: 1 },
      { x: 0, y: 2 },
      { x: 0, y: 3 },
      { x: 3, y: 3 },
    ],
    solution: [
      p(0, 1, 'horizontal'),
      p(2, 1, 'vertical'),
      p(3, 1, 'vertical'),
      p(4, 1, 'vertical'),
      p(0, 2, 'horizontal'),
      p(0, 3, 'horizontal'),
      p(3, 3, 'horizontal'),
    ],
    par: 7,
    lesson: 'Beacons may be placed only on the named origin cells.',
    note: 'Coverage still reaches other required cells. Origins are not the whole lattice.',
  }),
  define({
    id: 'bl-17-locked-tip',
    title: 'Locked tip',
    width: 5,
    height: 5,
    difficulty: 'constrained',
    required: plus(2, 2, 2),
    available: ['cross'],
    inventory: { cross: 4 },
    locked: [p(2, 0, 'cross', true)],
    solution: [p(2, 0, 'cross'), p(0, 2, 'cross'), p(3, 2, 'cross'), p(2, 4, 'cross')],
    par: 4,
    lesson: 'A locked Cross already covers its plus. Build around it.',
    note: 'The locked beacon cannot be removed. Finish the remaining arms.',
  }),
  define({
    id: 'bl-18-locked-corner',
    title: 'Locked corner',
    width: 5,
    height: 5,
    difficulty: 'constrained',
    required: uniqueCells(rect(0, 0, 4, 0), rect(2, 1, 2, 4)),
    available: ['cross', 'diagonal'],
    inventory: { cross: 3, diagonal: 2 },
    locked: [p(0, 0, 'cross', true)],
    solution: [p(0, 0, 'cross'), p(3, 0, 'cross'), p(2, 2, 'cross'), p(2, 4, 'diagonal')],
    par: 4,
    lesson: 'A locked corner Cross changes which mix still fits the tee.',
    note: 'Work around the lock instead of trying to replace it.',
  }),
  define({
    id: 'bl-19-blocked-lane',
    title: 'Blocked lane',
    width: 5,
    height: 5,
    difficulty: 'constrained',
    blocked: [
      { x: 2, y: 0 },
      { x: 2, y: 1 },
      { x: 2, y: 2 },
      { x: 2, y: 3 },
      { x: 2, y: 4 },
    ],
    available: ['horizontal', 'vertical'],
    inventory: { horizontal: 5, vertical: 4 },
    solution: [
      p(0, 0, 'horizontal'),
      p(0, 1, 'horizontal'),
      p(0, 2, 'horizontal'),
      p(0, 3, 'horizontal'),
      p(0, 4, 'horizontal'),
      p(3, 1, 'vertical'),
      p(3, 4, 'vertical'),
      p(4, 1, 'vertical'),
      p(4, 4, 'vertical'),
    ],
    par: 9,
    lesson: 'A blocked column is an obstacle. Coverage skips it and continues beyond.',
    componentNote: 'The blocked column splits the field into two halves that still share one inventory.',
    note: 'This is the first full-board obstacle. The lane is not outside the lattice.',
  }),
  define({
    id: 'bl-20-blocked-hub',
    title: 'Blocked hub',
    width: 5,
    height: 5,
    difficulty: 'constrained',
    blocked: [{ x: 2, y: 2 }],
    available: ['cross', 'horizontal', 'vertical'],
    inventory: { cross: 3, horizontal: 4, vertical: 4 },
    solution: [
      p(0, 0, 'cross'),
      p(2, 0, 'vertical'),
      p(3, 0, 'vertical'),
      p(4, 0, 'vertical'),
      p(1, 2, 'cross'),
      p(3, 2, 'horizontal'),
      p(0, 4, 'cross'),
      p(2, 3, 'vertical'),
      p(4, 3, 'horizontal'),
      p(4, 4, 'horizontal'),
    ],
    par: 10,
    lesson: 'A single blocked hub splits what a center Cross could have done.',
    note: 'The center is an obstacle, not a void cell.',
  }),
  define({
    id: 'bl-21-seven-ring',
    title: 'Seven ring',
    width: 7,
    height: 7,
    difficulty: 'advanced',
    required: uniqueCells(rect(0, 0, 6, 1), rect(0, 5, 6, 6), rect(0, 2, 1, 4), rect(5, 2, 6, 4)),
    available: ['cross', 'horizontal', 'vertical'],
    inventory: { cross: 6, horizontal: 8, vertical: 8 },
    solution: [
      p(0, 0, 'cross'),
      p(2, 0, 'vertical'),
      p(3, 0, 'vertical'),
      p(4, 0, 'vertical'),
      p(5, 0, 'vertical'),
      p(6, 0, 'vertical'),
      p(1, 2, 'cross'),
      p(5, 2, 'horizontal'),
      p(0, 4, 'cross'),
      p(5, 3, 'horizontal'),
      p(5, 4, 'horizontal'),
      p(2, 5, 'horizontal'),
      p(5, 5, 'horizontal'),
      p(0, 6, 'horizontal'),
      p(3, 6, 'horizontal'),
      p(6, 6, 'horizontal'),
    ],
    par: 16,
    lesson: 'A thick 7×7 ring leaves a void courtyard, not blocked obstacles.',
    note: 'The inner 3×3 is outside this lattice.',
  }),
  define({
    id: 'bl-22-seven-band',
    title: 'Seven band',
    width: 7,
    height: 7,
    difficulty: 'advanced',
    required: rect(0, 1, 6, 5),
    available: ['horizontal', 'vertical', 'cross'],
    inventory: { horizontal: 12, vertical: 12, cross: 6 },
    solution: [
      p(0, 1, 'horizontal'),
      p(2, 1, 'vertical'),
      p(3, 1, 'vertical'),
      p(4, 1, 'vertical'),
      p(5, 1, 'vertical'),
      p(6, 1, 'vertical'),
      p(0, 2, 'horizontal'),
      p(0, 3, 'horizontal'),
      p(3, 3, 'horizontal'),
      p(6, 3, 'horizontal'),
      p(0, 4, 'horizontal'),
      p(3, 4, 'horizontal'),
      p(6, 4, 'horizontal'),
      p(0, 5, 'horizontal'),
      p(3, 5, 'horizontal'),
      p(6, 5, 'horizontal'),
    ],
    par: 16,
    lesson: 'A five-row 7×7 band is a large connected lattice.',
    note: 'Use bars and Cross beacons together. The top and bottom rows are void.',
  }),
  define({
    id: 'bl-23-seven-field',
    title: 'Seven field',
    width: 7,
    height: 7,
    difficulty: 'advanced',
    available: ['cross', 'diagonal', 'horizontal', 'vertical'],
    inventory: { cross: 8, diagonal: 8, horizontal: 10, vertical: 10 },
    solution: [
      p(0, 0, 'cross'),
      p(2, 0, 'diagonal'),
      p(3, 0, 'diagonal'),
      p(5, 0, 'cross'),
      p(6, 2, 'cross'),
      p(0, 2, 'horizontal'),
      p(3, 2, 'horizontal'),
      p(0, 3, 'horizontal'),
      p(3, 3, 'horizontal'),
      p(5, 4, 'cross'),
      p(0, 4, 'horizontal'),
      p(2, 5, 'vertical'),
      p(3, 5, 'vertical'),
      p(0, 5, 'horizontal'),
      p(4, 6, 'vertical'),
      p(6, 6, 'cross'),
      p(0, 6, 'horizontal'),
    ],
    par: 17,
    lesson: 'The full 7×7 uses every cell and every beacon type.',
    note: 'There is no void frame on this board.',
  }),
  define({
    id: 'bl-24-seven-lock',
    title: 'Seven lock',
    width: 7,
    height: 7,
    difficulty: 'advanced',
    blocked: [{ x: 3, y: 3 }],
    available: ['cross', 'diagonal', 'horizontal', 'vertical'],
    inventory: { cross: 8, diagonal: 8, horizontal: 10, vertical: 10 },
    locked: [p(0, 0, 'cross', true)],
    solution: [
      p(0, 0, 'cross'),
      p(2, 0, 'diagonal'),
      p(3, 0, 'diagonal'),
      p(5, 0, 'cross'),
      p(6, 2, 'cross'),
      p(0, 2, 'horizontal'),
      p(3, 2, 'horizontal'),
      p(0, 3, 'horizontal'),
      p(2, 4, 'cross'),
      p(4, 3, 'horizontal'),
      p(0, 5, 'cross'),
      p(4, 5, 'cross'),
      p(6, 4, 'horizontal'),
      p(6, 6, 'cross'),
      p(2, 6, 'horizontal'),
    ],
    par: 15,
    lesson: 'A locked corner plus a blocked hub is the late-game constraint pair.',
    note: 'The center is blocked. The opening Cross is locked.',
  }),
];

export function getPuzzle(id: string): PuzzleDefinition | undefined {
  return PUZZLES.find((puzzle) => puzzle.id === id);
}

export function puzzleIndex(id: string): number {
  return PUZZLES.findIndex((puzzle) => puzzle.id === id);
}
