import { deal } from './deal';
import { reduce } from './engine';
import { loadSave, saveGame } from './persistence';
import { loadPref, savePref } from '../shared/storage';
import { play, setMuted } from '../shared/audio';
import type { Card, PileRef } from './model';
import './styles.css';

const ranks=['','Ace','2','3','4','5','6','7','8','9','10','Jack','Queen','King'];
const symbols={spades:'♠',hearts:'♥',diamonds:'♦',clubs:'♣'};
const label=(c:Card,pile:string,selected=false)=>`${ranks[c.rank]} of ${c.suit}, ${c.suit==='hearts'||c.suit==='diamonds'?'red':'black'}, ${c.faceUp?'face up':'face down'}, ${pile}${selected?', selected':''}`;
export function mountShatteredFoil(root:HTMLElement):()=>void{
 const saved=loadSave();let state=saved??deal(Date.now()>>>0), active=false, selected:{ref:PileRef;index:number}|null=null, announce='';
 state.preferences.leftHanded=loadPref('shattered-left',state.preferences.leftHanded);state.preferences.fourColor=loadPref('shattered-four',state.preferences.fourColor);state.preferences.muted=loadPref('muted',state.preferences.muted);setMuted(state.preferences.muted);
 const same=(a:PileRef,b:PileRef)=>a.type===b.type&&('index'in a?'index'in b&&a.index===b.index:true);
 const act=(action:Parameters<typeof reduce>[1],message='Move complete.')=>{active=true;const before=state;state=reduce(state,action);announce=state===before?'That move is not allowed.':message;if(state!==before)void play(state.won?'win':'blip');selected=null;saveGame(state);render();queueMicrotask(()=>root.querySelector<HTMLElement>(action.type==='undo'?'[data-action="undo"]':'[data-action="stock"]')?.focus());};
 const tryDestination=(to:PileRef)=>{if(!selected)return;act({type:'move',from:selected.ref,to,cardIndex:selected.index});};
 const cardButton=(c:Card,ref:PileRef,index:number,pileName:string)=>`<button class="sf-card ${c.faceUp?'is-up':'is-down'} ${selected&&same(selected.ref,ref)&&selected.index===index?'is-selected':''}" data-pile="${ref.type}" data-index="${'index'in ref?ref.index:''}" data-card="${index}" aria-label="${label(c,pileName,!!selected&&same(selected.ref,ref)&&selected.index===index)}" ${c.faceUp?'draggable="true"':'disabled'}><span>${c.faceUp?`${ranks[c.rank][0]??c.rank}${symbols[c.suit]}`:'◆'}</span></button>`;
 function render(){root.innerHTML=`<section class="sf ${state.preferences.leftHanded?'is-left':''} ${state.preferences.fourColor?'is-four':''}">
 <div class="sf-toolbar"><div><strong>Score ${state.score}</strong><span>Moves ${state.moves}</span><span data-time>${Math.floor(state.elapsed/60)}:${String(state.elapsed%60).padStart(2,'0')}</span></div><div>${!active?`<button class="btn btn--ghost btn--sm" data-action="start">${saved?'Resume':'Start'}</button>`:''}<button class="btn btn--ghost btn--sm" data-action="undo" ${state.history.length?'':'disabled'}>Undo</button><button class="btn btn--ghost btn--sm" data-action="restart">Restart</button><button class="btn btn--sm" data-action="new">New deal</button></div></div>
 <div class="sf-options"><label><input type="checkbox" data-pref="left" ${state.preferences.leftHanded?'checked':''}> Left-handed layout</label><label><input type="checkbox" data-pref="four" ${state.preferences.fourColor?'checked':''}> Four-color suits</label><label><input type="checkbox" data-pref="mute" ${state.preferences.muted?'checked':''}> Mute effects</label></div>
 <div class="sf-board" aria-label="Klondike solitaire board"><div class="sf-top">
 <button class="sf-pile sf-stock" data-action="stock" aria-label="${state.stock.length?`Stock, ${state.stock.length} cards`:'Empty stock, recycle waste'}">${state.stock.length?'◆':'↻'}</button>
 <div class="sf-pile sf-waste" data-destination="waste">${state.waste.length?cardButton(state.waste.at(-1)!,{type:'waste'},state.waste.length-1,'waste'):'<span>Waste</span>'}</div>
 <div class="sf-foundations">${state.foundations.map((p,i)=>`<button class="sf-pile sf-foundation" data-foundation="${i}" aria-label="Foundation ${i+1}${p.length?`, ${label(p.at(-1)!,'foundation')}`:', empty'}">${p.length?`${ranks[p.at(-1)!.rank][0]}${symbols[p.at(-1)!.suit]}`:'A'}</button>`).join('')}</div></div>
 <div class="sf-tableau">${state.tableau.map((p,col)=>`<div class="sf-column" data-tableau="${col}" role="group" aria-label="Tableau column ${col+1}">${p.map((c,i)=>cardButton(c,{type:'tableau',index:col},i,`tableau column ${col+1}`)).join('')}<button class="sf-drop" data-tableau="${col}" aria-label="Move selected cards to tableau column ${col+1}"></button></div>`).join('')}</div></div>
 <p class="sf-help">Select a face-up card or sequence, then choose a tableau column or foundation. Escape cancels.</p><p class="sr-only" aria-live="polite">${announce}${state.won?' You won Shattered Foil.':''}</p></section>`;
 bind();}
 function bind(){root.querySelectorAll<HTMLElement>('[data-card]').forEach(el=>el.addEventListener('click',()=>{const type=el.dataset.pile!;const ref:PileRef=type==='waste'?{type:'waste'}:{type:'tableau',index:Number(el.dataset.index)};const index=Number(el.dataset.card);if(selected){tryDestination(ref);}else{selected={ref,index};announce='Card selected. Choose a destination.';render();}}));
 root.querySelectorAll<HTMLElement>('[data-card][draggable="true"]').forEach(el=>el.addEventListener('dragstart',()=>{const type=el.dataset.pile!;selected={ref:type==='waste'?{type:'waste'}:{type:'tableau',index:Number(el.dataset.index)},index:Number(el.dataset.card)};}));
 root.querySelectorAll<HTMLElement>('[data-tableau]').forEach(el=>{el.addEventListener('click',e=>{if((e.target as HTMLElement).closest('[data-card]'))return;tryDestination({type:'tableau',index:Number(el.dataset.tableau)});});el.addEventListener('dragover',e=>e.preventDefault());el.addEventListener('drop',e=>{e.preventDefault();tryDestination({type:'tableau',index:Number(el.dataset.tableau)});});});root.querySelectorAll<HTMLElement>('[data-foundation]').forEach(el=>el.addEventListener('click',()=>tryDestination({type:'foundation',index:Number(el.dataset.foundation)})));
 root.querySelector('[data-action="start"]')?.addEventListener('click',()=>{active=true;state.started=true;announce=saved?'Saved deal resumed.':'Deal started.';saveGame(state);render();queueMicrotask(()=>root.querySelector<HTMLElement>('[data-action="stock"]')?.focus());});
 root.querySelector('[data-action="stock"]')?.addEventListener('click',()=>act({type:state.stock.length?'draw':'recycle'},state.stock.length?'Drew one card.':'Recycled the waste.'));root.querySelector('[data-action="undo"]')?.addEventListener('click',()=>act({type:'undo'},'Move undone.'));root.querySelector('[data-action="restart"]')?.addEventListener('click',()=>{state=deal(state.seed);active=true;state.started=true;announce='Deal restarted.';saveGame(state);render();queueMicrotask(()=>root.querySelector<HTMLElement>('[data-action="stock"]')?.focus());});root.querySelector('[data-action="new"]')?.addEventListener('click',()=>{state=deal(Date.now()>>>0);active=true;state.started=true;announce='New deal started.';saveGame(state);render();queueMicrotask(()=>root.querySelector<HTMLElement>('[data-action="stock"]')?.focus());});
 root.querySelectorAll<HTMLInputElement>('[data-pref]').forEach(el=>el.addEventListener('change',()=>{if(el.dataset.pref==='left'){state.preferences.leftHanded=el.checked;savePref('shattered-left',el.checked);}else if(el.dataset.pref==='four'){state.preferences.fourColor=el.checked;savePref('shattered-four',el.checked);}else{state.preferences.muted=el.checked;savePref('muted',el.checked);setMuted(el.checked);}saveGame(state);render();}));}
 const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'&&selected){selected=null;announce='Selection canceled.';render();}};document.addEventListener('keydown',onKey);render();
 const timer=window.setInterval(()=>{const blocked=document.hidden||document.querySelector('[data-consent-banner]:not([hidden]),[data-consent-modal]:not([hidden])');if(active&&state.started&&!state.won&&!blocked){state.elapsed++;saveGame(state);const el=root.querySelector('[data-time]');if(el)el.textContent=`${Math.floor(state.elapsed/60)}:${String(state.elapsed%60).padStart(2,'0')}`;}},1000);
 return()=>{clearInterval(timer);document.removeEventListener('keydown',onKey);root.innerHTML='';};
}
