/**
 * Lights Out rules for the NoCharge calm edition.
 *
 * Pure functions only. Boards are always generated by pressing from a solved
 * state, so every puzzle is solvable by construction — stated honestly in the
 * guide. NoCharge does not claim these puzzles train anything.
 */

export const LIGHTS_SIZE = 5;

export type LightsBoard = boolean[][];

export interface LightsState {
  board: LightsBoard;
  moves: number;
  status: 'playing' | 'won';
}

export function makeBoard(): LightsBoard {
  return Array.from({ length: LIGHTS_SIZE }, () => Array.from({ length: LIGHTS_SIZE }, () => false));
}

export function cloneBoard(board: LightsBoard): LightsBoard {
  return board.map((row) => [...row]);
}

export function inBounds(row: number, col: number): boolean {
  return row >= 0 && row < LIGHTS_SIZE && col >= 0 && col < LIGHTS_SIZE;
}

/** Toggle a cell and its orthogonal neighbours; returns a new board. */
export function press(board: LightsBoard, row: number, col: number): LightsBoard {
  if (!inBounds(row, col)) return board;
  const next = cloneBoard(board);
  for (const [dr, dc] of [[0, 0], [-1, 0], [1, 0], [0, -1], [0, 1]]) {
    const r = row + dr;
    const c = col + dc;
    if (inBounds(r, c)) next[r]![c] = !next[r]![c];
  }
  return next;
}

export function litCount(board: LightsBoard): number {
  return board.flat().filter(Boolean).length;
}

export function isSolved(board: LightsBoard): boolean {
  return board.every((row) => row.every((cell) => !cell));
}

/** Generate a solvable puzzle by pressing `presses` random cells from solved. */
export function generatePuzzle(random = Math.random, presses = 12): LightsBoard {
  let board = makeBoard();
  for (let index = 0; index < presses; index += 1) {
    const row = Math.floor(random() * LIGHTS_SIZE);
    const col = Math.floor(random() * LIGHTS_SIZE);
    board = press(board, row, col);
  }
  // Avoid trivial puzzles (all off already).
  if (isSolved(board)) board = press(board, 2, 2);
  return board;
}

export function newGame(random = Math.random): LightsState {
  return { board: generatePuzzle(random), moves: 0, status: 'playing' };
}

export function applyPress(state: LightsState, row: number, col: number): LightsState {
  if (state.status === 'won' || !inBounds(row, col)) return state;
  const board = press(state.board, row, col);
  return {
    board,
    moves: state.moves + 1,
    status: isSolved(board) ? 'won' : 'playing',
  };
}

export function cellName(row: number, col: number): string {
  return `Row ${row + 1}, Column ${col + 1}`;
}
