import{shuffle}from'../deal';import{colorOf,type Card}from'../model';
export interface FreeCellState{mode:'freecell';seed:number;cascades:Card[][];cells:(Card|null)[];foundations:Card[][];moves:number;score:number;history:FreeCellState[]}
export function dealFreeCell(seed:number):FreeCellState{const d=shuffle(seed).map(c=>({...c,faceUp:true})),cascades=Array.from({length:8},()=>[] as Card[]);d.forEach((c,i)=>cascades[i%8].push(c));return{mode:'freecell',seed,cascades,cells:[null,null,null,null],foundations:[[],[],[],[]],moves:0,score:0,history:[]};}
export const freeCellCapacity=(s:FreeCellState,to:number)=>{const cells=s.cells.filter(c=>!c).length,empty=s.cascades.filter((p,i)=>!p.length&&i!==to).length;return(cells+1)*2**empty;};
export const validFreeCellSequence=(cs:Card[])=>cs.every((c,i)=>i===0||cs[i-1].rank===c.rank+1&&colorOf(cs[i-1])!==colorOf(c));
export function canMoveFreeCellSequence(s:FreeCellState,cards:Card[],to:number){if(!cards.length||cards.length>freeCellCapacity(s,to)||!validFreeCellSequence(cards))return false;const top=s.cascades[to].at(-1);return !top||top.rank===cards[0].rank+1&&colorOf(top)!==colorOf(cards[0]);}
export function moveFreeCellCascade(s:FreeCellState,from:number,index:number,to:number){const cards=s.cascades[from]?.slice(index)??[];if(!canMoveFreeCellSequence(s,cards,to))return s;const n=structuredClone(s);n.history=[...s.history,{...structuredClone(s),history:[]}];n.cascades[from].splice(index);n.cascades[to].push(...cards);n.moves++;return n;}
export function cascadeToCell(s:FreeCellState,from:number,cell:number){if(s.cells[cell]||!s.cascades[from]?.length)return s;const n=structuredClone(s);n.history=[...s.history,{...structuredClone(s),history:[]}];n.cells[cell]=n.cascades[from].pop()!;n.moves++;return n;}
export function cellToCascade(s:FreeCellState,cell:number,to:number){const card=s.cells[cell];if(!card||!canMoveFreeCellSequence(s,[card],to))return s;const n=structuredClone(s);n.history=[...s.history,{...structuredClone(s),history:[]}];n.cascades[to].push(card);n.cells[cell]=null;n.moves++;return n;}
export function freeCellToFoundation(s:FreeCellState,source:{type:'cascade'|'cell';index:number},foundation:number){const card=source.type==='cascade'?s.cascades[source.index]?.at(-1):s.cells[source.index],target=s.foundations[foundation];if(!card)return s;const top=target.at(-1);if(top?top.suit!==card.suit||card.rank!==top.rank+1:card.rank!==1)return s;const n=structuredClone(s);n.history=[...s.history,{...structuredClone(s),history:[]}];const moving=source.type==='cascade'?n.cascades[source.index].pop()!:n.cells[source.index]!;if(source.type==='cell')n.cells[source.index]=null;n.foundations[foundation].push(moving);n.moves++;n.score+=10;return n;}
export function freeCellWon(s:FreeCellState){return s.foundations.every(p=>p.length===13);}
