import{shuffle}from'../deal';import type{Card}from'../model';
export interface PyramidState{mode:'pyramid';seed:number;pyramid:(Card|null)[];stock:Card[];waste:Card[];score:number;moves:number;history:PyramidState[]}
const rowStart=(r:number)=>r*(r+1)/2;export function pyramidChildren(index:number){let row=0;while(rowStart(row+1)<=index)row++;if(row===6)return[];const pos=index-rowStart(row),next=rowStart(row+1);return[next+pos,next+pos+1];}
export function dealPyramid(seed:number):PyramidState{const d=shuffle(seed).map(c=>({...c,faceUp:true}));return{mode:'pyramid',seed,pyramid:d.splice(0,28),stock:d,waste:[],score:0,moves:0,history:[]};}
export function isPyramidExposed(s:PyramidState,index:number){return !!s.pyramid[index]&&pyramidChildren(index).every(i=>!s.pyramid[i]);}
export function removePyramid(s:PyramidState,a:number,b?:number){const ca=s.pyramid[a];if(!ca||!isPyramidExposed(s,a))return s;const valid=b===undefined?ca.rank===13:(!!s.pyramid[b]&&isPyramidExposed(s,b)&&ca.rank+s.pyramid[b]!.rank===13);if(!valid)return s;const n=structuredClone(s);n.history=[...s.history,{...structuredClone(s),history:[]}];n.pyramid[a]=null;if(b!==undefined)n.pyramid[b]=null;n.score+=b===undefined?13:20;n.moves++;return n;}
export function removePyramidWithWaste(s:PyramidState,index:number){const card=s.pyramid[index],waste=s.waste.at(-1);if(!card||!waste||!isPyramidExposed(s,index)||card.rank+waste.rank!==13)return s;const n=structuredClone(s);n.history=[...s.history,{...structuredClone(s),history:[]}];n.pyramid[index]=null;n.waste.pop();n.score+=20;n.moves++;return n;}
export function removeWasteKing(s:PyramidState){if(s.waste.at(-1)?.rank!==13)return s;const n=structuredClone(s);n.history=[...s.history,{...structuredClone(s),history:[]}];n.waste.pop();n.score+=13;n.moves++;return n;}
export function drawPyramid(s:PyramidState){if(!s.stock.length)return s;const n=structuredClone(s);n.history=[...s.history,{...structuredClone(s),history:[]}];n.waste.push(n.stock.pop()!);n.moves++;return n;}
export const pyramidWon=(s:PyramidState)=>s.pyramid.every(c=>!c);export const pyramidLost=(s:PyramidState)=>!s.stock.length&&!s.pyramid.some((c,i)=>c&&isPyramidExposed(s,i)&&(c.rank===13||s.pyramid.some((d,j)=>d&&j!==i&&isPyramidExposed(s,j)&&c.rank+d.rank===13)));
