import { createDeck, seededRandom } from '../deal';import type{Card}from'../model';
export interface SpiderState{mode:'spider';seed:number;tableau:Card[][];stock:Card[];completed:Card[][];moves:number;score:number;history:SpiderState[]}
export function dealSpider(seed:number,suits:1|2|4=4):SpiderState{let deck=[...createDeck(),...createDeck().map(c=>({...c,id:`2-${c.id}`}))];if(suits<4){const allowed=suits===1?['spades']:['spades','hearts'];deck=deck.map((c,i)=>({...c,suit:allowed[i%allowed.length] as Card['suit'],id:`${i}-${allowed[i%allowed.length]}-${c.rank}`}));}const r=seededRandom(seed);for(let i=deck.length-1;i;i--){const j=Math.floor(r()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]];}const tableau=Array.from({length:10},(_,col)=>Array.from({length:col<4?6:5},()=>deck.pop()!));tableau.forEach(p=>p.at(-1)!.faceUp=true);return{mode:'spider',seed,tableau,stock:deck,completed:[],moves:0,score:500,history:[]};}
export const isPackedSpiderRun=(cards:Card[])=>cards.every((c,i)=>c.faceUp&&(i===0||cards[i-1].rank===c.rank+1&&cards[i-1].suit===c.suit));
export function canMoveSpider(cards:Card[],target:Card[]){if(!cards.length||!isPackedSpiderRun(cards))return false;const top=target.at(-1);return !top||top.rank===cards[0].rank+1;}
export function dealSpiderRow(state:SpiderState){if(state.stock.length<10||state.tableau.some(p=>!p.length))return state;const next=structuredClone(state);next.history=[...state.history,{...structuredClone(state),history:[]}];for(const p of next.tableau){const c=next.stock.pop()!;c.faceUp=true;p.push(c);}next.moves++;return clearRuns(next);}
export function moveSpider(state:SpiderState,from:number,index:number,to:number){const cards=state.tableau[from]?.slice(index)??[];if(!canMoveSpider(cards,state.tableau[to]??[]))return state;const n=structuredClone(state);n.history=[...state.history,{...structuredClone(state),history:[]}];n.tableau[from].splice(index);n.tableau[to].push(...cards);const exposed=n.tableau[from].at(-1);if(exposed)exposed.faceUp=true;n.moves++;n.score=Math.max(0,n.score-1);return clearRuns(n);}
export function clearRuns(state:SpiderState){for(const pile of state.tableau){const run=pile.slice(-13);if(run.length===13&&run[0].rank===13&&run.at(-1)!.rank===1&&isPackedSpiderRun(run)){pile.splice(-13);state.completed.push(run);state.score+=100;pile.at(-1)!.faceUp=true;}}return state;}
export const spiderWon=(s:SpiderState)=>s.completed.length===8;
