/**
 * Curated Nonogram puzzle library.
 * 12 puzzles for 5×5 and 12 puzzles for 10×10.
 * Themed: animals, food, shapes, simple objects (general audience).
 * Each puzzle has a unique solution (validated by solver tests).
 */
import type { PuzzleDefinition } from './engine';

function grid(rows: string[]): boolean[][] {
  return rows.map((row) => row.split('').map((c) => c === '#'));
}

export const PUZZLES_5x5: PuzzleDefinition[] = [
  {
    id: 'heart',
    size: 5,
    title: 'Heart',
    theme: 'shapes',
    solution: grid([
      '.#.#.',
      '#####',
      '#####',
      '.###.',
      '..#..',
    ]),
  },
  {
    id: 'star',
    size: 5,
    title: 'Star',
    theme: 'shapes',
    solution: grid([
      '..#..',
      '.###.',
      '#####',
      '.#.#.',
      '#...#',
    ]),
  },
  {
    id: 'fish',
    size: 5,
    title: 'Fish',
    theme: 'animals',
    solution: grid([
      '..#..',
      '.###.',
      '#####',
      '.###.',
      '..#..',
    ]),
  },
  {
    id: 'house',
    size: 5,
    title: 'House',
    theme: 'objects',
    solution: grid([
      '..#..',
      '.###.',
      '#####',
      '#.#.#',
      '#.#.#',
    ]),
  },
  {
    id: 'mushroom',
    size: 5,
    title: 'Mushroom',
    theme: 'food',
    solution: grid([
      '.###.',
      '#####',
      '..#..',
      '.###.',
      '.###.',
    ]),
  },
  {
    id: 'cherry',
    size: 5,
    title: 'Cherry',
    theme: 'food',
    solution: grid([
      '..#..',
      '.#.#.',
      '#...#',
      '#...#',
      '.#.#.',
    ]),
  },
  {
    id: 'cat',
    size: 5,
    title: 'Cat',
    theme: 'animals',
    solution: grid([
      '#...#',
      '#####',
      '.###.',
      '.#.#.',
      '.###.',
    ]),
  },
  {
    id: 'diamond',
    size: 5,
    title: 'Diamond',
    theme: 'shapes',
    solution: grid([
      '..#..',
      '.###.',
      '#####',
      '.###.',
      '..#..',
    ]),
  },
  {
    id: 'cup',
    size: 5,
    title: 'Cup',
    theme: 'objects',
    solution: grid([
      '#####',
      '#...#',
      '.#.#.',
      '.###.',
      '..#..',
    ]),
  },
  {
    id: 'apple',
    size: 5,
    title: 'Apple',
    theme: 'food',
    solution: grid([
      '..#..',
      '.###.',
      '#####',
      '#####',
      '.###.',
    ]),
  },
  {
    id: 'cross',
    size: 5,
    title: 'Cross',
    theme: 'shapes',
    solution: grid([
      '..#..',
      '..#..',
      '#####',
      '..#..',
      '..#..',
    ]),
  },
  {
    id: 'tree',
    size: 5,
    title: 'Tree',
    theme: 'objects',
    solution: grid([
      '..#..',
      '.###.',
      '#####',
      '..#..',
      '..#..',
    ]),
  },
];

export const PUZZLES_10x10: PuzzleDefinition[] = [
  {
    id: 'smiley',
    size: 10,
    title: 'Smiley',
    theme: 'shapes',
    solution: grid([
      '..######..',
      '.########.',
      '##.####.##',
      '##########',
      '##########',
      '#.######.#',
      '#..####..#',
      '.#......#.',
      '..######..',
      '..........',
    ]),
  },
  {
    id: 'boat',
    size: 10,
    title: 'Boat',
    theme: 'objects',
    solution: grid([
      '....##....',
      '...####...',
      '..######..',
      '.########.',
      '##########',
      '##########',
      '.########.',
      '..######..',
      '...####...',
      '....##....',
    ]),
  },
  {
    id: 'butterfly',
    size: 10,
    title: 'Butterfly',
    theme: 'animals',
    solution: grid([
      '##......##',
      '####..####',
      '##########',
      '.########.',
      '..######..',
      '..######..',
      '.########.',
      '##########',
      '####..####',
      '##......##',
    ]),
  },
  {
    id: 'umbrella',
    size: 10,
    title: 'Umbrella',
    theme: 'objects',
    solution: grid([
      '..######..',
      '.########.',
      '##########',
      '##########',
      '....##....',
      '....##....',
      '....##....',
      '....##....',
      '...###....',
      '..###.....',
    ]),
  },
  {
    id: 'flower',
    size: 10,
    title: 'Flower',
    theme: 'objects',
    solution: grid([
      '....##....',
      '...####...',
      '..##..##..',
      '.##.##.##.',
      '..##..##..',
      '...####...',
      '....##....',
      '....##....',
      '...####...',
      '..######..',
    ]),
  },
  {
    id: 'arrow',
    size: 10,
    title: 'Arrow',
    theme: 'shapes',
    solution: grid([
      '....##....',
      '...####...',
      '..######..',
      '.########.',
      '##########',
      '....##....',
      '....##....',
      '....##....',
      '....##....',
      '....##....',
    ]),
  },
  {
    id: 'cake',
    size: 10,
    title: 'Cake',
    theme: 'food',
    solution: grid([
      '...####...',
      '...####...',
      '.########.',
      '.########.',
      '##########',
      '##########',
      '##########',
      '##########',
      '.########.',
      '.########.',
    ]),
  },
  {
    id: 'anchor',
    size: 10,
    title: 'Anchor',
    theme: 'objects',
    solution: grid([
      '....##....',
      '...####...',
      '....##....',
      '..######..',
      '....##....',
      '....##....',
      '.##.##.##.',
      '#..####..#',
      '.#......#.',
      '..######..',
    ]),
  },
  {
    id: 'crab',
    size: 10,
    title: 'Crab',
    theme: 'animals',
    solution: grid([
      '##......##',
      '.##....##.',
      '..######..',
      '.########.',
      '##########',
      '##.####.##',
      '#..####..#',
      '...####...',
      '..##..##..',
      '.##....##.',
    ]),
  },
  {
    id: 'sun',
    size: 10,
    title: 'Sun',
    theme: 'shapes',
    solution: grid([
      '....##....',
      '.#..##..#.',
      '..######..',
      '.########.',
      '####..####',
      '.########.',
      '..######..',
      '.#..##..#.',
      '....##....',
      '..........',
    ]),
  },
  {
    id: 'leaf',
    size: 10,
    title: 'Leaf',
    theme: 'objects',
    solution: grid([
      '.......##.',
      '......####',
      '.....#####',
      '....######',
      '...#######',
      '..#######.',
      '.######...',
      '#####.....',
      '####......',
      '##........',
    ]),
  },
  {
    id: 'key',
    size: 10,
    title: 'Key',
    theme: 'objects',
    solution: grid([
      '..####....',
      '.######...',
      '##..####..',
      '.######...',
      '..####....',
      '....##....',
      '....####..',
      '....##....',
      '....####..',
      '....##....',
    ]),
  },
];

export const ALL_PUZZLES: PuzzleDefinition[] = [...PUZZLES_5x5, ...PUZZLES_10x10];

export function getPuzzle(id: string): PuzzleDefinition | undefined {
  return ALL_PUZZLES.find((p) => p.id === id);
}

export function getPuzzleByIndex(index: number): PuzzleDefinition {
  return ALL_PUZZLES[index % ALL_PUZZLES.length]!;
}
