import type { GameState } from '../model';

export const DB_NAME = 'nocharge-shattered-foil';
export const DB_VERSION = 1;
export const STORE_NAMES = ['profiles','settings','sessions','dailyChallenges','streaks','progression','inventory','journey','moveHistory','migrations'] as const;
export type StoreName = typeof STORE_NAMES[number];
export type Mode = 'klondike'|'spider'|'freecell'|'tripeaks'|'pyramid';
export interface SessionRecord { id:string; mode:Mode; version:1; dealSeed:number; state:unknown; score:number; moves:number; elapsedMs:number; undoHistory:unknown[]; startedAt:string; updatedAt:string; completedAt:string|null; status:'active'|'won'|'lost' }
export interface SettingsRecord { id:'preferences'; activeMode:Mode; drawMode:1|3; atmosphere:'dark'|'sapphire'|'amethyst'|'obsidian'; cardBack:string; leftHanded:boolean; fourColorSuits:boolean; musicEnabled:boolean; musicVolume:number; sfxEnabled:boolean; sfxVolume:number; hapticsEnabled:boolean; autoRotateMusic:boolean; activeTrack:string }
export interface ProgressionRecord { id:'main'; shards:number; stars:number; unlockedRealms:string[]; completedJourneyDeals:string[]; earnedBadges:string[] }
export interface InventoryRecord { id:'owned'; atmospheres:string[]; cardBacks:string[]; themes:string[]; equippedAtmosphere:string; equippedCardBack:string }
export interface ExportBundle { format:'nocharge-shattered-foil'; version:1; exportedAt:string; stores:Partial<Record<StoreName,unknown[]>> }

const memory = new Map<StoreName,Map<IDBValidKey,unknown>>();
for(const name of STORE_NAMES)memory.set(name,new Map());
let fallback=false;
export function validateSession(value:unknown):value is SessionRecord{if(!value||typeof value!=='object')return false;const v=value as Partial<SessionRecord>;return v.version===1&&typeof v.id==='string'&&['klondike','spider','freecell','tripeaks','pyramid'].includes(v.mode??'')&&typeof v.dealSeed==='number'&&typeof v.score==='number'&&typeof v.moves==='number';}
export function validateImport(value:unknown):value is ExportBundle{if(!value||typeof value!=='object')return false;const v=value as Partial<ExportBundle>;return v.format==='nocharge-shattered-foil'&&v.version===1&&!!v.stores&&typeof v.stores==='object';}
function request<T>(req:IDBRequest<T>):Promise<T>{return new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
export async function openDatabase():Promise<IDBDatabase|null>{if(typeof indexedDB==='undefined'){fallback=true;return null;}return new Promise(resolve=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const db=req.result;for(const name of STORE_NAMES)if(!db.objectStoreNames.contains(name))db.createObjectStore(name,{keyPath:name==='dailyChallenges'?'dateKey':'id'});req.transaction?.objectStore('migrations').put({id:'v1',appliedAt:new Date().toISOString(),description:'Initial multi-mode schema'});};req.onsuccess=()=>resolve(req.result);req.onerror=()=>{fallback=true;resolve(null)};req.onblocked=()=>{fallback=true;resolve(null)};});}
export async function putRecord<T extends {id?:string;dateKey?:string}>(store:StoreName,value:T){const db=await openDatabase();if(!db){const key=value.id??value.dateKey;if(key){memory.get(store)!.set(key,value);try{localStorage.setItem(`nocharge:sf-fallback:${store}:${String(key)}`,JSON.stringify(value));}catch{}}return;}await new Promise<void>((resolve,reject)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).put(value);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});db.close();}
export async function getRecord<T>(store:StoreName,key:IDBValidKey):Promise<T|null>{const db=await openDatabase();if(!db){const cached=memory.get(store)!.get(key) as T|undefined;if(cached)return cached;try{const raw=localStorage.getItem(`nocharge:sf-fallback:${store}:${String(key)}`);return raw?JSON.parse(raw) as T:null;}catch{return null;}}const value=await request(db.transaction(store).objectStore(store).get(key));db.close();return (value as T)??null;}
export async function getAllRecords<T>(store:StoreName):Promise<T[]>{const db=await openDatabase();if(!db){const values=new Map<string,T>();for(const [key,value] of memory.get(store)!)values.set(String(key),value as T);try{for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key?.startsWith(`nocharge:sf-fallback:${store}:`)){const raw=localStorage.getItem(key);if(raw)values.set(key.split(':').at(-1)!,JSON.parse(raw) as T);}}}catch{}return[...values.values()];}const values=await request(db.transaction(store).objectStore(store).getAll());db.close();return values as T[];}
export async function deleteRecord(store:StoreName,key:IDBValidKey){const db=await openDatabase();if(!db){memory.get(store)!.delete(key);try{localStorage.removeItem(`nocharge:sf-fallback:${store}:${String(key)}`);}catch{}return;}await new Promise<void>((resolve,reject)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).delete(key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});db.close();}
export async function clearAllGameData(){const db=await openDatabase();if(!db){for(const map of memory.values())map.clear();try{const keys=[];for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key?.startsWith('nocharge:sf-fallback:'))keys.push(key);}keys.forEach(key=>localStorage.removeItem(key));}catch{}return;}await new Promise<void>((resolve,reject)=>{const tx=db.transaction([...STORE_NAMES],'readwrite');for(const name of STORE_NAMES)tx.objectStore(name).clear();tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});db.close();try{const keys=[];for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key?.startsWith('nocharge:sf-fallback:'))keys.push(key);}keys.forEach(key=>localStorage.removeItem(key));}catch{}}
export async function exportGameData():Promise<ExportBundle>{const stores:ExportBundle['stores']={};for(const name of STORE_NAMES)stores[name]=await getAllRecords(name);return{format:'nocharge-shattered-foil',version:1,exportedAt:new Date().toISOString(),stores};}
export async function importGameData(value:unknown){if(!validateImport(value))throw new Error('Unsupported or invalid Shattered Foil export.');for(const name of STORE_NAMES){const records=value.stores[name]??[];if(!Array.isArray(records))throw new Error(`Invalid ${name} records.`);if(name==='sessions'&&records.some(record=>!validateSession(record)))throw new Error('Invalid session record.');}for(const name of STORE_NAMES)for(const record of value.stores[name]??[])await putRecord(name,record as {id?:string;dateKey?:string});}
export async function completeDailyTransaction(record:{dateKey:string;mode:Mode;seed:number;score:number;moves:number;elapsedMs:number}){const db=await openDatabase();if(!db)throw new Error('Daily persistence unavailable.');return new Promise<void>((resolve,reject)=>{const tx=db.transaction(['dailyChallenges','streaks','progression'],'readwrite'),daily=tx.objectStore('dailyChallenges'),streaks=tx.objectStore('streaks'),progress=tx.objectStore('progression'),existing=daily.get(record.dateKey);existing.onsuccess=()=>{if(existing.result)return;daily.put({...record,status:'completed',completedAt:new Date().toISOString()});const sr=streaks.get('daily');sr.onsuccess=()=>{const current=sr.result??{id:'daily',current:0,longest:0,lastCompletedDate:null,monthlyCompletionKeys:[]};const previous=new Date(`${record.dateKey}T00:00:00Z`);previous.setUTCDate(previous.getUTCDate()-1);current.current=current.lastCompletedDate===previous.toISOString().slice(0,10)?current.current+1:1;current.longest=Math.max(current.longest,current.current);current.lastCompletedDate=record.dateKey;current.monthlyCompletionKeys=[...new Set([...current.monthlyCompletionKeys,record.dateKey])];streaks.put(current);};const pr=progress.get('main');pr.onsuccess=()=>{const p=pr.result??{id:'main',shards:120,stars:0,unlockedRealms:['botanical'],completedJourneyDeals:[],earnedBadges:[]};p.stars+=1;p.shards+=20;progress.put(p);};};tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)};});}
export async function purchaseInventoryItem(item:{id:string;cost:number;type:'cardBack'|'atmosphere'|'theme'}){const db=await openDatabase();if(!db)throw new Error('Persistent inventory is unavailable in this browser.');return new Promise<'purchased'|'owned'|'insufficient'>((resolve,reject)=>{const tx=db.transaction(['progression','inventory'],'readwrite'),ps=tx.objectStore('progression'),is=tx.objectStore('inventory'),pr=ps.get('main'),ir=is.get('owned');let result:'purchased'|'owned'|'insufficient'='insufficient';pr.onsuccess=()=>{ir.onsuccess=()=>{const p=(pr.result as ProgressionRecord|undefined)??{id:'main',shards:120,stars:0,unlockedRealms:['botanical'],completedJourneyDeals:[],earnedBadges:[]};const i=(ir.result as InventoryRecord|undefined)??{id:'owned',atmospheres:['dark','sapphire','amethyst','obsidian'],cardBacks:['copper_foil','cathedral_azure'],themes:['classic'],equippedAtmosphere:'dark',equippedCardBack:'copper_foil'};const key=item.type==='cardBack'?'cardBacks':item.type==='atmosphere'?'atmospheres':'themes';if(i[key].includes(item.id)){result='owned';return;}if(p.shards<item.cost){result='insufficient';return;}p.shards-=item.cost;i[key].push(item.id);if(item.type==='cardBack')i.equippedCardBack=item.id;if(item.type==='atmosphere')i.equippedAtmosphere=item.id;ps.put(p);is.put(i);result='purchased';};};tx.oncomplete=()=>{db.close();resolve(result)};tx.onerror=()=>{db.close();reject(tx.error)};});}
export const isFallbackStorage=()=>fallback;
export function klondikeSession(state:GameState):SessionRecord{return{id:'klondike-active',mode:'klondike',version:1,dealSeed:state.seed,state,score:state.score,moves:state.moves,elapsedMs:state.elapsed*1000,undoHistory:state.history,startedAt:new Date().toISOString(),updatedAt:new Date().toISOString(),completedAt:state.won?new Date().toISOString():null,status:state.won?'won':'active'};}
