export interface Point { row:number; col:number }
export interface Placement { word:string; start:Point; end:Point }
export interface WordSearchPuzzle { size:number; grid:string[][]; placements:Placement[]; words:string[]; seed:number }
const DIRS=[[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]] as const;
const fallback=['cat','dog','fish','bear','lion','horse','mouse','rabbit','tiger','eagle','whale','shark'];
function rng(seed:number){let n=seed>>>0; return ()=>{n=(n*1664525+1013904223)>>>0;return n/4294967296;};}
export function safeWords(words:unknown):string[]{if(!Array.isArray(words))return fallback.slice();const clean=words.filter(x=>typeof x==='string').map(x=>x.trim().toLowerCase()).filter(x=>/^[a-z]+$/.test(x)&&x.length>1);return clean.length===12?clean:fallback.slice();}
export function createPuzzle(words:unknown=fallback,size=8,seed=Date.now()):WordSearchPuzzle{size=size===10?10:8; const list=safeWords(words).sort((a,b)=>b.length-a.length);const random=rng(seed);let placements:Placement[]=[];let grid:string[][]=[];for(let attempt=0;attempt<40;attempt++){grid=Array.from({length:size},()=>Array(size).fill(''));placements=[];let ok=true;for(const word of list){const choices=DIRS.map(([dr,dc])=>({dr,dc})).sort(()=>random()-.5);let placed=false;for(const {dr,dc} of choices){for(let tries=0;tries<80&&!placed;tries++){const r=Math.floor(random()*size),c=Math.floor(random()*size),er=r+dr*(word.length-1),ec=c+dc*(word.length-1);if(er<0||er>=size||ec<0||ec>=size)continue;let valid=true;for(let i=0;i<word.length;i++){const old=grid[r+dr*i][c+dc*i];if(old&&old!==word[i]){valid=false;break;}}if(valid){for(let i=0;i<word.length;i++)grid[r+dr*i][c+dc*i]=word[i];placements.push({word,start:{row:r,col:c},end:{row:er,col:ec}});placed=true;}}if(placed)break;}if(!placed){ok=false;break;}}if(ok)break;}
const letters='abcdefghijklmnopqrstuvwxyz';for(let r=0;r<size;r++)for(let c=0;c<size;c++)if(!grid[r][c])grid[r][c]=letters[Math.floor(random()*letters.length)];return {size,grid,placements,words:list,seed};}
export function sameLine(a:Point,b:Point){const dr=Math.sign(b.row-a.row),dc=Math.sign(b.col-a.col);return (dr===0||dc===0||Math.abs(b.row-a.row)===Math.abs(b.col-a.col))&&!(a.row===b.row&&a.col===b.col);}
export function selectedWord(puzzle:WordSearchPuzzle,start:Point,end:Point):string|null{if(!sameLine(start,end))return null;const dr=Math.sign(end.row-start.row),dc=Math.sign(end.col-start.col);const length=Math.max(Math.abs(end.row-start.row),Math.abs(end.col-start.col))+1;const text=Array.from({length},(_,i)=>puzzle.grid[start.row+dr*i]?.[start.col+dc*i]??'').join('');return puzzle.words.find(w=>w===text||w===text.split('').reverse().join(''))??null;}
export function isComplete(found:string[],words:string[]){return words.every(w=>found.includes(w));}
